feat(condo): DOMA-6513 check TLS cert before auth in SBBOL (#3537)
* feat(condo): DOMA-6513 check TLS cert before auth in SBBOL

* feat(condo): DOMA-6513 replaced page to modal

* feat(condo): DOMA-6513 separate page /tls with instructions to install TLS certificate

* refactor(condo): DOMA-6513 fixes in /tls page

* refactor(condo): DOMA-6513 added guides for Linux, Android, IOS. Fixed CSS styles

* refactor(condo): DOMA-6513 fixed callback functions in LoginWithSBBOLButton

* fix(condo): DOMA-6513 fixed import issue of '*.md' files into JSX

Error TS2307 was thrown by TypeScript compiler

* fix(condo): DOMA-6513 removed redundant and deprecated import of style constants

* fix(condo): DOMA-6513 removed redundant CSS style in favour of Space.gap

* fix(condo): DOMA-6513 typos in translations

* fix(condo): DOMA-6513 added "LoginWithSbbol" button to "tls" page

* fix(condo): DOMA-6513 changed texts in poster of "tls" page

* fix(condo): DOMA-6513 tweaked layout of text in poster in "tls" page

* feat(condo): DOMA-6513 extracted LoginWithSBBOLButton to separate module and implemented new visual style

* feat(condo): DOMA-6513 replaced styled div with emotion to constant of type React.CSSProperties

* refactor(condo): DOMA-6513 removed unnecessary code and added a comment

* fix(condo): DOMA-6513 replaced icon for "doma" in LoginWithSBBOLButton

* refactor(condo): DOMA-6513 removed unused PosterLayoutVertical component

* refactor(condo): DOMA-6513 used getServerSideProps to build content for installation guides depending of "accept-language" request header

* refactor(condo): DOMA-6513 fixes after rebase

* refactor(condo): DOMA-6513 fixed question icon position

* refactor(condo): DOMA-6513 fixed locale detection

* refactor(condo): DOMA-6513 fixed positioning of more link in poster

* refactor(condo): DOMA-6513 changed implementation of loading translated guides content files

* refactor(condo): DOMA-6513 improved typing

* refactor(condo): DOMA-6513 deleted declaration of ".md" files as modules in next-env.d.ts

* refactor(condo): DOMA-6513 rolled back changes in test RegExp in webpack config

* refactor(condo): DOMA-6513 rolled back changes in package.json after deprecating of importing ".md" files from "lang" folder

* refactor(condo): DOMA-6513 rebased yarn.lock

* refactor(condo): DOMA-6513 fixed types mismatch in props functions in LoginWithSBBOLButton

* refactor(condo): DOMA-6513 changed imports

* refactor(condo): DOMA-6513 changed RegExp for matching file name of translated guide section

* fix(condo): DOMA-6513 added fallback to string with empty object if 'CHECK_TLS_CLIENT_CERT_CONFIG' .env variable is not set

* feat(condo): DOMA-6513 added CHECK_TLS_CLIENT_CERT_CONFIG env to .helm

* refactor(condo): DOMA-6513 fixed issue with kind of "user input" vulnerability, found by SemGrep

* refactor(condo): DOMA-6513 used "raw-loader" for ".md" files to omit parsing errors by server start